/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Escola;

import GUI.ConsultasEscola;
import Business_Layer.Utilizador;
import GUI.Header.JEntrar;
import GUI.Home2;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author miguelpinto
 */
public class EscolasMenuAdmin extends javax.swing.JPanel {

    private Home2 root;
    
    public EscolasMenuAdmin(Home2 aThis, Utilizador user) {
       initComponents();
       this.root = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultas = new javax.swing.JButton();
        addEscola = new javax.swing.JButton();
        editarEscola = new javax.swing.JButton();
        removerEscola = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 247, 247));

        consultas.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        consultas.setText("Consultar");
        consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasActionPerformed(evt);
            }
        });

        addEscola.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addEscola.setText("Adicionar");
        addEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEscolaActionPerformed(evt);
            }
        });

        editarEscola.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        editarEscola.setText("Editar");
        editarEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEscolaActionPerformed(evt);
            }
        });

        removerEscola.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        removerEscola.setText("Remover");
        removerEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerEscolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editarEscola, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(addEscola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(consultas, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(removerEscola, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(addEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(editarEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(removerEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasActionPerformed
        // TODO add your handling code here:
        String str = this.root.devolveSeleccionadosEscolas();
        
        if(str != null) {
            JFrame frame = new ConsultasEscola(this.root,str);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        } 
    }//GEN-LAST:event_consultasActionPerformed

    private void editarEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEscolaActionPerformed
        // TODO add your handling code here:
        String str = this.root.devolveSeleccionadosEscolas();
        
        if(str != null) {
            JDialog frame = new jEditarEscola(this.root,str);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_editarEscolaActionPerformed

    private void addEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEscolaActionPerformed
        // TODO add your handling code here:
        JDialog frame = new jCriarEscola(this.root);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_addEscolaActionPerformed

    private void removerEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerEscolaActionPerformed
        // TODO add your handling code here:
        String str = this.root.devolveSeleccionadosEscolas();
        
        if(str != null) {
            JDialog frame = new jRemoverEscola(this.root,str);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_removerEscolaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEscola;
    private javax.swing.JButton consultas;
    private javax.swing.JButton editarEscola;
    private javax.swing.JButton removerEscola;
    // End of variables declaration//GEN-END:variables
}
