/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Escola;

import Business_Layer.Equipa;
import Business_Layer.Escola;
import Business_Layer.Utilizador;
import GUI.Home2;
import GUI.Plantel.JPlantelAgenda;
import GUI.Plantel.JPlantelDadosEstatisticos;
import GUI.Plantel.JPlantelJogador;
import GUI.Plantel.JPlantelTreinador;
import java.awt.BorderLayout;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author miguelpinto
 */
public final class jConsultasEscola extends javax.swing.JFrame {

    private Home2 root;
    private Escola esc;
    private Utilizador user;
    
    public jConsultasEscola(Home2 root, String str) {
        this.root = root;
        this.esc = this.root.getSistema().getEscolas().get(str);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.root.setEnabled(true);
        
        reloadDetalhes();
        ativarComboEscolas();
        reloadOpcaoTreinadorConvidado();
        
    }
    
    public void reloadDetalhes() {
        this.panelGeralEscolas.setBorder(javax.swing.BorderFactory.createTitledBorder(esc.getNome()));
        this.local.setText("Local: " +esc.getLocal());
        this.campo.setText("Campo de Jogo: " +esc.getCampo().getNome());
    }
    
    public void ativarComboEscolas() {
        DefaultComboBoxModel<String> dcb = new DefaultComboBoxModel<>();
        
        for(String s : this.esc.getEquipas().keySet())
            dcb.addElement(s);
        
        this.comboEquipas.setModel(dcb);
    }
    
    public void reloadOpcaoTreinadorConvidado() {
        this.jPanelPlantel.removeAll();
        this.jPanelPlantel.add(this.jPanelOpcoes, BorderLayout.NORTH);
        this.jPanelPlantel.add(new JPlantelTreinador(this.root,this.user));
        this.jPanelPlantel.updateUI();
        this.jPanelPlantel.validate();
    }
    
    public void reloadOpcaoJogadoresConvidado() {
        this.jPanelPlantel.removeAll();
        this.jPanelPlantel.add(this.jPanelOpcoes, BorderLayout.NORTH);
        this.jPanelPlantel.add(new JPlantelJogador(this.root,this.user));
        this.jPanelPlantel.updateUI();
        this.jPanelPlantel.validate();
    }
    
    public void reloadOpcaoAgendaConvidado() {
        this.jPanelPlantel.removeAll();
        this.jPanelPlantel.add(this.jPanelOpcoes, BorderLayout.NORTH);
        this.jPanelPlantel.add(new JPlantelAgenda(this.root,this.user));
        this.jPanelPlantel.updateUI();
        this.jPanelPlantel.validate();
    }
    
    public void reloadOpcaoDadosEstConvidado() {
        this.jPanelPlantel.removeAll();
        this.jPanelPlantel.add(this.jPanelOpcoes, BorderLayout.NORTH);
        this.jPanelPlantel.add(new JPlantelDadosEstatisticos(this.root,this.user));
        this.jPanelPlantel.updateUI();
        this.jPanelPlantel.validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        panelUsers = new javax.swing.JPanel();
        panelGeralEscolas = new javax.swing.JPanel();
        jPanelDetalhesEscolaConvidado = new javax.swing.JPanel();
        local = new javax.swing.JLabel();
        campo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        comboEquipas = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jPanelPlantel = new javax.swing.JPanel();
        jPanelOpcoes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonTreinador = new javax.swing.JButton();
        jButtonJogadores = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jButtonDadosEst = new javax.swing.JButton();
        jPanelPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APEF - Menu Consultas");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        header.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Associação Portuguesa de Escolas de Futebol");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        panelSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSearch.setPreferredSize(new java.awt.Dimension(1022, 52));

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanel1.add(panelSearch, java.awt.BorderLayout.PAGE_END);

        panelUsers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelUsers.setPreferredSize(new java.awt.Dimension(1022, 52));

        javax.swing.GroupLayout panelUsersLayout = new javax.swing.GroupLayout(panelUsers);
        panelUsers.setLayout(panelUsersLayout);
        panelUsersLayout.setHorizontalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
        );
        panelUsersLayout.setVerticalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanel1.add(panelUsers, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelGeralEscolas.setBorder(javax.swing.BorderFactory.createTitledBorder("Escola XX"));
        panelGeralEscolas.setLayout(new java.awt.BorderLayout());

        jPanelDetalhesEscolaConvidado.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes"));

        local.setText("Local:");

        campo.setText("Campo de Jogo:");

        javax.swing.GroupLayout jPanelDetalhesEscolaConvidadoLayout = new javax.swing.GroupLayout(jPanelDetalhesEscolaConvidado);
        jPanelDetalhesEscolaConvidado.setLayout(jPanelDetalhesEscolaConvidadoLayout);
        jPanelDetalhesEscolaConvidadoLayout.setHorizontalGroup(
            jPanelDetalhesEscolaConvidadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesEscolaConvidadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(local, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        jPanelDetalhesEscolaConvidadoLayout.setVerticalGroup(
            jPanelDetalhesEscolaConvidadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesEscolaConvidadoLayout.createSequentialGroup()
                .addGroup(jPanelDetalhesEscolaConvidadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(local, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelGeralEscolas.add(jPanelDetalhesEscolaConvidado, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(new org.jdesktop.swingx.border.IconBorder());

        jLabel4.setText("Seleccione uma Equipa");

        comboEquipas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Equipa 1", "Equipa 2", "Item 3", "Item 4" }));
        comboEquipas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEquipasActionPerformed(evt);
            }
        });

        jButton7.setText("Palmarés");
        jButton7.setToolTipText("");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboEquipas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEquipas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelGeralEscolas.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanelPlantel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Plantel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanelPlantel.setLayout(new java.awt.BorderLayout());

        jPanelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jLabel6.setText("Seleccione um escalão");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonTreinador.setText("Treinador");
        jButtonTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreinadorActionPerformed(evt);
            }
        });

        jButtonJogadores.setText("Jogadores");
        jButtonJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogadoresActionPerformed(evt);
            }
        });

        jButtonAgenda.setText("Agenda");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });

        jButtonDadosEst.setText("Dados Estatisticos");
        jButtonDadosEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadosEstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcoesLayout = new javax.swing.GroupLayout(jPanelOpcoes);
        jPanelOpcoes.setLayout(jPanelOpcoesLayout);
        jPanelOpcoesLayout.setHorizontalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                        .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButtonTreinador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jButtonJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addComponent(jButtonAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonDadosEst, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanelOpcoesLayout.setVerticalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDadosEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButtonTreinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonJogadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        jPanelPlantel.add(jPanelOpcoes, java.awt.BorderLayout.PAGE_START);

        jLabel1.setText("jPanelPanel");

        javax.swing.GroupLayout jPanelPanelLayout = new javax.swing.GroupLayout(jPanelPanel);
        jPanelPanel.setLayout(jPanelPanelLayout);
        jPanelPanelLayout.setHorizontalGroup(
            jPanelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(802, Short.MAX_VALUE))
        );
        jPanelPanelLayout.setVerticalGroup(
            jPanelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jPanelPlantel.add(jPanelPanel, java.awt.BorderLayout.CENTER);

        panelGeralEscolas.add(jPanelPlantel, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelGeralEscolas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEquipasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEquipasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEquipasActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreinadorActionPerformed
        // TODO add your handling code here:
        reloadOpcaoTreinadorConvidado();
    }//GEN-LAST:event_jButtonTreinadorActionPerformed

    private void jButtonJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogadoresActionPerformed
        // TODO add your handling code here:
        reloadOpcaoJogadoresConvidado();
    }//GEN-LAST:event_jButtonJogadoresActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        // TODO add your handling code here:
        reloadOpcaoAgendaConvidado();
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jButtonDadosEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadosEstActionPerformed
        // TODO add your handling code here:
        reloadOpcaoDadosEstConvidado();
    }//GEN-LAST:event_jButtonDadosEstActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campo;
    private javax.swing.JComboBox comboEquipas;
    private javax.swing.JLabel header;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonDadosEst;
    private javax.swing.JButton jButtonJogadores;
    private javax.swing.JButton jButtonTreinador;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelDetalhesEscolaConvidado;
    private javax.swing.JPanel jPanelOpcoes;
    private javax.swing.JPanel jPanelPanel;
    private javax.swing.JPanel jPanelPlantel;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel local;
    private javax.swing.JPanel panelGeralEscolas;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelUsers;
    // End of variables declaration//GEN-END:variables
}
