/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Campeonato;

import Business_Layer.Campeonato;
import Business_Layer.Jogo;
import Business_Layer.Jornada;
import Business_Layer.Utilizador;
import GUI.Home2;
import java.util.Map;

/**
 *
 * @author Utilizador
 */
public class JCampeonatoCalendario extends javax.swing.JPanel {

    private Home2 root;
    private int ano;
    
    public JCampeonatoCalendario(Home2 aThis, Utilizador user, int ano) {
        this.root = aThis;
        this.ano = ano;
        initComponents();
        
        Campeonato get = this.root.getSistema().getEpocas().get(2013).getCampeonatos().get(0);
        System.out.println(get.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCal = new org.jdesktop.swingx.JXTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Calendário"));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableCal.setBackground(new java.awt.Color(235, 235, 235));
        tableCal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Jornada", "Equipa Casa", "vs", "Equipa Visitante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCal.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tableCal.setRowHeight(20);
        tableCal.setRowMargin(2);
        tableCal.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableCal);
        if (tableCal.getColumnModel().getColumnCount() > 0) {
            tableCal.getColumnModel().getColumn(0).setResizable(false);
            tableCal.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableCal.getColumnModel().getColumn(1).setResizable(false);
            tableCal.getColumnModel().getColumn(1).setPreferredWidth(110);
            tableCal.getColumnModel().getColumn(2).setResizable(false);
            tableCal.getColumnModel().getColumn(2).setPreferredWidth(140);
            tableCal.getColumnModel().getColumn(3).setResizable(false);
            tableCal.getColumnModel().getColumn(3).setPreferredWidth(110);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable tableCal;
    // End of variables declaration//GEN-END:variables
}
