/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Equipa;

import Business_Layer.Equipa;
import Business_Layer.Escola;
import Business_Layer.Utilizador;
import GUI.ConsultasEscola;
import GUI.Equipa.jAdicionarEquipa;
import GUI.Escola.jPalmares;
import GUI.Home2;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;

/**
 *
 * @author miguelpinto
 */
public class JOpcoesAdmin extends javax.swing.JPanel {

    private ConsultasEscola cEscola;
    private Home2 root;
    private Utilizador user;
    private Escola escola;

    public JOpcoesAdmin(ConsultasEscola aThis, Home2 root, Escola esc, Utilizador user, ConsultasEscola aThis0) {
        this.cEscola = aThis;
        this.root = root;
        this.escola = esc;
        this.user = user;
        initComponents();
        
        ComboEscolas();
    }

    public void ComboEscolas() {
        DefaultComboBoxModel<String> dcb = new DefaultComboBoxModel<>();
        
        for(String s : this.escola.getEquipas().keySet())
            dcb.addElement(s);
        
        this.comboEquipas1.setModel(dcb);
    }
    
    public JComboBox getCombo() {
        return this.comboEquipas1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEquipas = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboEquipas1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        palmares = new javax.swing.JButton();
        adicionarEquipa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        avataer = new org.jdesktop.swingx.JXImageView();

        comboEquipas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Equipa 1", "Equipa 2", "Item 3", "Item 4" }));
        comboEquipas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEquipasActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccione uma Equipa");

        comboEquipas1.setSelectedItem(comboEquipas1.getSelectedItem());
        comboEquipas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEquipas1ActionPerformed(evt);
            }
        });

        palmares.setText("Palmarés");
        palmares.setToolTipText("");
        palmares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palmaresActionPerformed(evt);
            }
        });

        adicionarEquipa.setText("Adicionar");
        adicionarEquipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEquipaActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar Imagem");

        remover.setText("Remover");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout avataerLayout = new javax.swing.GroupLayout(avataer);
        avataer.setLayout(avataerLayout);
        avataerLayout.setHorizontalGroup(
            avataerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        avataerLayout.setVerticalGroup(
            avataerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(remover, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(palmares, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adicionarEquipa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(avataer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addComponent(comboEquipas1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jSeparator1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEquipas1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avataer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adicionarEquipa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(palmares, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboEquipasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEquipasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEquipasActionPerformed

    private void palmaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palmaresActionPerformed
        // TODO add your handling code here:
        String str = (String) this.comboEquipas.getSelectedItem();
        
        if(str != null) {
            JDialog frame = new jPalmares(this.root, this.escola.getEquipas().get(str), str);
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_palmaresActionPerformed

    private void adicionarEquipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEquipaActionPerformed
        // TODO add your handling code here:
        JDialog frame = new jAdicionarEquipa(this.root, this.user, this.escola,this);
        frame.setVisible(true);
        
        this.cEscola.reloadPanelEquipaGeral(null);
    }//GEN-LAST:event_adicionarEquipaActionPerformed

    private void comboEquipas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEquipas1ActionPerformed
        // TODO add your handling code here:
        String s = (String) this.comboEquipas1.getSelectedItem();
        
        if(s != null) {
            cEscola.reloadPanelEquipaGeral(s);
        }
    }//GEN-LAST:event_comboEquipas1ActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        // TODO add your handling code here:
        String equipa = (String) this.comboEquipas1.getSelectedItem();
        
        if(equipa != null) {
        Equipa e = escola.getEquipas().get(equipa);
        JDialog frame = new JRemoverEquipa(this.root, this.user, this.escola,this,e);
        frame.setVisible(true);
        }
    }//GEN-LAST:event_removerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarEquipa;
    private org.jdesktop.swingx.JXImageView avataer;
    private javax.swing.JComboBox comboEquipas;
    private javax.swing.JComboBox comboEquipas1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton palmares;
    private javax.swing.JButton remover;
    // End of variables declaration//GEN-END:variables
}
